### PR TITLE
Expose functions to bypass zip file bundles

### PR DESCRIPTION
**Pull request by krousey**
This exposes creating a gocql.HostDialer directly from an *astra.Bundle and not needed a zip file. This also let's users create a cluster with these custom Dialers.

### CODE REVIEW

**Comment by qzg** [comment]
Note that the only methods currently exposed both leverage the SCB.  There needs to be a way to supply credentials directly for users which need to manage their own creds but also need the benefit of this custom dialer.

**Comment by krousey** [comment]
`NewDialer` takes an [`*astra.Bundle`](https://pkg.go.dev/github.com/datastax/cql-proxy/astra#Bundle) as a parameter which is defined to be:

```go
type Bundle struct {
	TLSConfig *tls.Config
	Host      string
	Port      int
}
```

This is easy enough to supply directly without dealing the ZIP files of the bundles.

**Comment by joao-r-reis** [comment]
Thanks for the contribution!

Have you signed the Contributor License Agreement for contributions to DataStax open source projects? If not you can find it at https://cla.datastax.com/. Thanks!

**Comment by krousey** [comment]
I signed it.

**Comment by absurdfarce** [comment]
Excellent @krousey!  Thanks for the contribution!

**Comment by absurdfarce** [comment]
Hey @krousey, we're working on clarifying the license and copyright terms for gocq-astra.  We'd like to explicitly make this code available under ASL (see [this PR](https://github.com/datastax/gocql-astra/pull/13) for more on that).  As part of that effort I'd like confirm that you're okay with the addition of the copyright assignment statement to source files that include the changes you made in this PR.

Feel free to reply by just posting a comment here; that's probably the most straightforward way to do it.  Also please ask away if you have any questions.

Thanks!

**Pull request merged**
